version: '3.3'

services:
  blog-app:
    build: ./
    command: ./wait-for-postgres.sh database ./blog-app
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DB_PASSWORD=qwerty
      - AUTH_TOKEN=token

  database:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432